### ISSUE TITLE
Can not change the description of the activity

### ISSUE THREAD

**Issue by SteffenPegenau** [moodlepeers/moodle-mod_groupformation#15] opened 2016-10-12 09:04 UTC
It is not possible to change the description of a groupformation after a student has answered the questionnaire. 

If this is intended, the teacher should get a message that he/she can not change the description. But I currently don't see a reason why this should be forbidden... :confused:

**Comment by rroepke** [comment] 2016-10-12 20:19
Commit: 7c2caa62e6bfbc697aba26d7c7981d90f02fe409

The problem is now fixed; manually fixing the problem can be done simply by adding the following line

`$origrecord->intro = $groupformation->intro;
`

**after line 135 in lib.php**. For more details review commit.

**Closed by rroepke** 2016-10-12 20:19 UTC
